name: Add CNAME

on: deployment

jobs:
  create-cname:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Create CNAME file
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "CNAME"
        FILE_DATA: "eduardstefanescu.dev"
    - name: Add & Commit
      uses: EndBug/add-and-commit@v5.2.0
      with:
        branch: master
        message: 'Added CNAME'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
